Try to create the phone home dir if we're superuser
If we're the superuser, we should try to create this directory since we
have the power to do so.

diff --git a/activate b/activate
--- a/activate
+++ b/activate
@@ -27,7 +27,14 @@
 DIR="/var/lib/eos-phone-home"
 if [ ! -d "${DIR}" ] || [ ! -w "${DIR}" ]; then
     echo "${DIR} missing or not writable"
-    exit 1
+
+    if [ "$EUID" == "0" ]; then
+      echo "Making ${dir}"
+      mkdir -p /var/lib/eos-phone-home
+    else
+      echo "Not root user so we can't even create the folder. Exiting."
+      exit 1
+    fi
 fi
 
 # Give me a ping, Vasili. One ping only, please.
